---
apiVersion: v1
kind: Service
metadata:
  name: mq-mp-ws-svc
  namespace: legacy
spec:
  selector:
    app: mq-mp
  ports:
  - name: mq-mp-ws
    protocol: TCP
    port: 80
    targetPort: 8081
...