---
  - name: Uploading lobby
    copy:
      src: "{{ build_root }}/max-quest-ror-lobby.tar.gz"
      dest: "/home/users/{{ user }}/deploy/max-quest-ror-lobby.tar.gz"

  - name: Uploading game
    copy:
      src: "{{ build_root }}/max-quest-ror-game.tar.gz"
      dest: "/home/users/{{ user }}/deploy/max-quest-ror-game.tar.gz"

  - name: Removing old backup
    file:
      path: "/www/html/{{ lobby_name }}/html5pc/actiongames{{ cluster }}/revengeofra/_backup"
      state: absent

  - name: Creating dir for backup
    file:
      path: "/www/html/{{ lobby_name }}/html5pc/actiongames{{ cluster }}/revengeofra/_backup"
      state: directory

  - name: Creating lobby backup
    shell: "mv /www/html/{{ lobby_name }}/html5pc/actiongames{{ cluster }}/revengeofra/lobby/ /www/html/{{ lobby_name }}/html5pc/actiongames{{ cluster }}/revengeofra/_backup/lobby/"

  - name: Creating dir for lobby
    file:
      path: "/www/html/{{ lobby_name }}/html5pc/actiongames{{ cluster }}/revengeofra/lobby/"
      state: directory

  - name: Extracting lobby
    shell: "tar -xzf /home/users/{{ user }}/deploy/max-quest-ror-lobby.tar.gz -C /www/html/{{ lobby_name }}/html5pc/actiongames{{ cluster }}/revengeofra/lobby/"

  - name: Creating game backup
    shell: "mv /www/html/{{ lobby_name }}/html5pc/actiongames{{ cluster }}/revengeofra/game/ /www/html/{{ lobby_name }}/html5pc/actiongames{{ cluster }}/revengeofra/_backup/game/"

  - name: Creating dir for game
    file:
      path: "/www/html/{{ lobby_name }}/html5pc/actiongames{{ cluster }}/revengeofra/game/"
      state: directory

  - name: Extracting game
    shell: "tar -xzf /home/users/{{ user }}/deploy/max-quest-ror-game.tar.gz -C /www/html/{{ lobby_name }}/html5pc/actiongames{{ cluster }}/revengeofra/game/"

