---
apiVersion: v1
kind: Service
metadata:
  name: mq-gs-internal-svc
  namespace: legacy
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.103.0.210
  selector:
    app: mq-gs
  ports:
  - name: mq-gs
    protocol: TCP
    port: 80
    targetPort: 8080
...
