---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-gs
  namespace: legacy
spec:
  selector:
    matchLabels:
      app: mq-gs
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: mq-gs
        env: dev01
        app-env: mq-gs-dev01
    spec:
      affinity:
        # nodeAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     nodeSelectorTerms:
        #     - matchExpressions:
        #       - key: custom-node-label-key
        #         operator: In
        #         values:
        #         - preemptible
        # nodeAffinity:
        #   preferredDuringSchedulingIgnoredDuringExecution:
        #   - weight: 1
        #     preference:
        #       matchExpressions:
        #       - key: custom-node-label-key
        #         operator: In
        #         values:
        #         - preemptible
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mq-gs
            topologyKey: "kubernetes.io/hostname"
        # podAntiAffinity:
        #   preferredDuringSchedulingIgnoredDuringExecution:
        #   - weight: 1
        #     podAffinityTerm:
        #       labelSelector:
        #         matchExpressions:
        #         - key: app
        #           operator: In
        #           values:
        #           - mq-gs
        #       topologyKey: "kubernetes.io/hostname"
      # terminationGracePeriodSeconds: 60
      # serviceAccountName: md-dev01-legacy
      containers:
      - name: mq-gs
        image: europe-west1-docker.pkg.dev/maxduel-dev01/md-dev01/mq-gs-test:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        # envFrom:
        # - configMapRef:
        #     name: mq-gs
        # - secretRef:
        #     name: mq-gs
        resources:
          requests:
            cpu:    250m
            memory: 1000Mi
          limits:
            cpu:    500m
            memory: 2000Mi
        # startupProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 2
        #   periodSeconds: 15
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 2
        #   periodSeconds: 15
        #   timeoutSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 2
        #   periodSeconds: 15
        #   timeoutSeconds: 10
...
